Tracking/Controllers/BonusController.cs
using Microsoft.AspNetCore.Mvc;
using Tracking.Models;

namespace Tracking.Controllers
{
    public class BonusController : Controller
    {
        public IActionResult Index()
        {
            var context = new BonustrackingContext();
            var employeeId = int.Parse(HttpContext.Session.GetString("Id"));
            var result = context.Bonus.Where(x => x.EmployeeId == employeeId).ToList(); ;
            return View(result);
        }
    }
}

Tracking/Controllers/ObjectionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tracking.Models;
using Tracking.ViewModels;

namespace Tracking.Controllers
{
    public class ObjectionController : Controller
    {
        public IActionResult Index()
        {
            var context = new BonustrackingContext();
            var employeeId = int.Parse(HttpContext.Session.GetString("Id"));
            var result = context.GetObjectionsByEmployeeId.FromSqlRaw("EXECUTE dbo.GetObjectionsByEmployeeId {0}", employeeId).ToList();
            if (result.Count > 0)
            {
                result = result.OrderByDescending(x => x.ObjectionDate).ToList();
            }
            return View(result);
        }

        public IActionResult CreateObjection(int bonusId)
        {
            var model = new CreateObjectionViewModel();
            model.BonusId = bonusId;
            return View(model);
        }

        [HttpPost]
        public IActionResult CreateObjection(CreateObjectionViewModel model)
        {
            var context = new BonustrackingContext();
            context.Database.ExecuteSqlRaw("EXEC dbo.CreateObjectionSp @p0, @p1", parameters: new[] { model.BonusId.ToString(), model.Desc.ToString() });

            return RedirectToAction("Index"); 
        }

        public IActionResult TeamLeadIndex()
        {
            var context = new BonustrackingContext();
            var employeeId = int.Parse(HttpContext.Session.GetString("Id"));
            var result = context.ObjectionsForTeamLead.ToList();
            if (result.Count > 0)
            {
                result = result.OrderByDescending(x => x.ObjectionDate).ToList();
            }
            return View(result);
        }

        public IActionResult ObjectionReponseForTeamLead(int result,int objectionId)
        {

            return View(result);
        }
    }
}

Tracking/Controllers/SupportController.cs
using Microsoft.AspNetCore.Mvc;
using Tracking.Models;
using Tracking.ViewModels;

namespace Tracking.Controllers
{
    public class SupportController : Controller
    {
        public IActionResult Index()
        {
            var context = new BonustrackingContext();
            var employeeId = int.Parse(HttpContext.Session.GetString("Id"));
            var datas = context.SupportWithTimeDifferences.Where(x=>x.EmployeeId == employeeId).ToList();
            return View(datas);
        }

        public IActionResult CreateSupport()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateSupport(CreateSupportViewModel model)
        {
            var context = new BonustrackingContext();

            var support = context.Supports.Add(new Support()
            {
                CustomerFullName = model.CustomerFullName,
                StartDate = model.StartDate,
                EndDate = model.EndDate,
                Status = model.Status,
                Subject = model.Subject,
                EmployeeId = int.Parse(HttpContext.Session.GetString("Id"))
            });

            context.SaveChanges();

            if (model.Note != null)
            {
                context.SupportDetails.Add(new SupportDetail()
                {
                    Message = model.Note,
                    SupportId = support.Entity.Id
                });

                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

Tracking/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tracking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tracking.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tracking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetString("RoleId") == "1")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Support" asp-action="Index">Destek</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bonus" asp-action="Index">Prim</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Objection" asp-action="Index">İtiraz</a>
                            </li>
                        }
                        else if (Context.Session.GetString("RoleId") == "2")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Objection" asp-action="TeamLeadIndex">İtiraz</a>
                            </li>
                        }
                        else if (Context.Session.GetString("RoleId") == "3")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Objection" asp-action="GroupManagerIndex">İtiraz</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Login" asp-action="Index">Çıkış Yap</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Tracking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>